### PR TITLE
Fixup PR 2547

### PR DESCRIPTION
**Pull request by rhaschke**
This comprises two commits to fixup open issues in https://github.com/ros-planning/moveit/pull/2547.

### CODE REVIEW

**Comment by PeterMitrano** [comment]
works for me -- just to clarify though, the example you gave of 

```
import moveit
moveit.core.xxx
```

is expected to _not_ work, correct? Whereas `import moveit.core` and  `from moveit import core` still work as expected

once that's confirmed I'll merge this and push it to the main PR

**Comment by rhaschke** [comment]
Exactly.

**Comment by PeterMitrano** [comment]
@rhaschke I tried to extend the bindings to another package and somehow I'm running into this issue again, where the devel-space install doesn't work.

Right now both moveit_core and any new package (say moveit_ros_planning) both try to generate `devel/lib/python3/dist-packages/moveit/__init__.py` which are in conflict. I can't wrap my around how this was supposed to work? I really thought I tested it this already but I'm not sure. Any ideas?

**Comment by rhaschke** [comment]
I can confirm that devel-space install doesn't work yet, because of conflicting `__init__.py` files generated by catkin during build.
These generated files inject the source path of the current package into the python search path, such that the source files are found when importing from devel space. However, this scheme doesn't work for namespaced packages. I'm not sure anybody is still maintaining the underlying catkin code :disappointed:

**Pull request merged**
